spring:
  application:
    name: video-upload-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/moviedb
    username: postgres
    password: renu
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.trusted.packages: "org.example.models"

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

kafka:
  topic:
    video-upload: video-uploads
    video-processing: video-processing

aws:
  s3:
    bucket-name: video-processing-platform-bucket
    region: ap-south-1

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8085

logging:
  level:
    com.example.videoupload: DEBUG